spring:
  security:
    user:
      name: user1
      password: password
  datasource:
    drive-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: name
    password: password
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: embedded
  jackson:
    serialization:
      indent-output: true
  thymeleaf:
    enable: true



