spring:
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: embedded
  security:
    user:
      name: user1
      password: password
  thymeleaf:
    enable: true
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
#logging:
#  level:
#    org:
#      springframework: DEBUG

